<?php
return array(
	'all' => 'All',
	'acolyte' => 'Acolyte',
	'alchemist' => 'Alchemist',
	'archer' => 'Archer',
	'assassin' => 'Assassin',
	'barddancer' => 'Bard or Dancer',
	'blacksmith' => 'Blacksmith',
	'crusader' => 'Crusader',
	'gunslinger' => 'Gunslinger',
	'hunter' => 'Hunter',
	'kagerouoboro' => 'Kagerou & Oboro',
	'knight' => 'Knight',
	'mage' => 'Mage',
	'merchant' => 'Merchant',
	'monk' => 'Monk',
	'ninja' => 'Ninja',
	'novice' => 'Novice',
	'priest' => 'Priest',
	'rebellion' => 'Rebellion',
	'rogue' => 'Rogue',
	'sage' => 'Sage',
	'soullinker' => 'Soul Linker',
	'stargladiator' => 'Star Gladiator',
	'summoner' => 'Summoner',
	'supernovice' => 'Super Novice',
	'swordman' => 'Swordman',
	'taekwon' => 'Taekwon',
	'thief' => 'Thief',
	'wizard' => 'Wizard',
)
?>